### PR TITLE
Support configuration for languages

### PR DESCRIPTION
**Pull request by galangel**
Not tested, just something i wish for, for you to decide.

### CODE REVIEW

**Comment by chrmarti** [comment]
Thanks for the PR @galangel!

One issue is that the extension only activates on known languages:
https://github.com/chrmarti/vscode-regex/blob/b04f25238600763d0dc9c3bd77b08c772a470ebf/package.json#L23

Which languages are you interested in specifically? Currently only a few regex formats are detected.

**Comment by galangel** [comment]
I mainly use jsx and tsx files, so javascript regex is good, but I had to manually change the language mode to typescript to have it working .

**Comment by chrmarti** [comment]
Let's just add these two languages then. Other languages would only work well if they had the same regex syntax.

**Comment by chrmarti** [comment]
Please also add the two languages to the package.json: https://github.com/chrmarti/vscode-regex/blob/b04f25238600763d0dc9c3bd77b08c772a470ebf/package.json#L23

**Pull request merged**
